### ISSUE TITLE
wrong example

### ISSUE THREAD

**Issue by durka** [mashlol/notify#1]
The readme says `cmd || notify` will fire the notification whether or not the command succeeds, but actually it only fires if the command returns 1 (which by convention means failure).

```bash
$ true || echo notify
$ false || echo notify
notify
$
```

**Comment by mashlol** [comment]
Ah whoops, we really want semi-colon then I believe.

**Comment by mashlol** [comment]
Fixed everywhere except the Android app, will get to that later.
