### ISSUE TITLE
Parse.com is shutting down

### ISSUE THREAD

**Issue by divergentdave** [mashlol/notify#12]
I noticed that this uses Parse.com, which is shutting down next year. Do you have plans for migrating the cloud service portion of this? The backend servers have now been mostly open sourced, see https://github.com/ParsePlatform/parse-server

**Comment by mashlol** [comment]
I'll have to investigate other hosting options, since I'd rather not pay for any servers for this.  I don't have any immediate plans though.

**Comment by mashlol** [comment]
Added support for Firebase and pushed new version to npm, still waiting on the Android app to be approved.  It should be available [here](https://play.google.com/store/apps/details?id=com.kevinbedi.notify) when it is approved.  Don't upgrade before installing the new app or you won't be able to send any pushes at all.

**Comment by divergentdave** [comment]
Nice, thanks for doing this!
