### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by plehr** [mashlol/notify#13]
I use multiple devices. So I would like to send one message to my phone & tablet.
Is it possible to edit the  .notifyreg file for more than one device?

Like this:
token123
token321

Thanks

**Comment by giorger** [comment]
Hi Plehr,

Tried a quick and dirty solution #14 which worked out and notified me on both mobiles.
Applied the changes described in #14 and then appended lines into ".notifyreg" as you mention and it worked.

**Comment by mashlol** [comment]
@giorger  thanks for the quick solution!

@plehr I'm going to be updating with Firebase soon since Parse is shutting down, and in the rewrite I'll add better support for this.

**Comment by plehr** [comment]
@giorger @mashlol Thank you for your efforts

**Comment by mashlol** [comment]
Pushed the Firebase update (and also added official support for this feature) to npm, waiting on the Android app to be uploaded.  It should be available [here](https://play.google.com/store/apps/details?id=com.kevinbedi.notify) when it is approved.  Don't upgrade before installing the new app or you won't be able to send any pushes at all.
