### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by philthomson** [mashlol/notify#15]
Attempting to register my key on Arch Linux (notify -r [my key]) gives the above err msg.

**Comment by mashlol** [comment]
Does Arch Linux have env?  Perhaps it does not live in /usr/bin on Arch Linux?

**Comment by philthomson** [comment]
```$ which env
/usr/bin/env```

**Comment by mashlol** [comment]
Oh probably the \r is screwing it up...

**Comment by heyiswas** [comment]
Same here on Ubuntu (and Raspbian on a PI):

root@server:~# notify
/usr/bin/env: 'node\r': No such file or directory

I can see Windows symbols like `^M` at the end of each line, when I use `vim -b`. Is this an issue?

root@server:~# which env
/usr/bin/env

root@server:~# uname -a
Linux d6bc404348d5 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mashlol** [comment]
Should be fixed in 0.1.3 now.
