### ISSUE TITLE
App: Avoid to generate a key contain the letters:  l, 1, I

### ISSUE THREAD

**Issue by weyou** [mashlol/notify#18]
If the letters [l, 1, I] are in the same key, for some fonts, it's difficult to distinguish them.  So please avoid to generate the key contains [l, 1, I] or you can show the key with a clear font.

**Comment by szpeter80** [comment]
Dear Kevin,

thanks for this great app! I used the old version, now installed the new one, but it still gives I or L characters upon the key generation. Do i miss something?
