### ISSUE TITLE
/bin/sh on Ubuntu does not understand the [[ foo ]]  notation

### ISSUE THREAD

**Issue by szpeter80** [mashlol/notify#19]
When the script is executed, it outputs: "./notify.sh: 3: ./notify.sh: [[: not found"
Changing the shebang line to 

#!/bin/bash

resolves this problem. On Ubuntu and possibly also on Debian, the default shell is "dash" which had caused some headache not a long time ago for me when debugging shell script behaviour.

hope this helps

regards,

Peter

**Comment by mashlol** [comment]
Do you want to submit a pull request to update this?

**Comment by szpeter80** [comment]
Hi,
thanks for picking up this issue. I was not sure if the proposed solution lines up with the project plan, but if you think this modification is acceptable, i will try. I have to admit, i use github via the SVN interface, so it might take a little time to pick up git-style workflow.

**Comment by mashlol** [comment]
Yes I think your solution would be fine.
