### ISSUE TITLE
Channel Name

### ISSUE THREAD

**Issue by kyluke** [mashlol/notify#3]
Hey man, really cool project. I've registered my device and get

    [notify] Your registration code has been saved to ~/.notifyreg

However, when testing this I run

    ls -l ; notify

and get the following error:

    [notify] Encountered an error: { code: 141, message: 'Error 112: Channel name must start with a letter: '}

I won't submit my identifier here but it does start with a 2. Is this causing an issue? Can I re-create a key?

Thanks man.

**Comment by mjdubell** [comment]
[notify] Encountered an error: { code: 141, message: 'Error 112: Channel name must start with a letter: <key>' }

Getting the same error.

**Comment by mashlol** [comment]
Thanks for reporting guys, this should be fixed now if you update to 0.0.3 using npm.

**Comment by kyluke** [comment]
I can confirm that this works
