### ISSUE TITLE
Nothing Happens

### ISSUE THREAD

**Issue by stellarpower** [mashlol/notify#32]
I've installed the cli but after registering the device and sending a notification nothing happens. I get no notification and in both cases the cli just exits silently.

**Comment by mashlol** [comment]
When you registered, did it print "[notify] Your registration code has been saved to ~/.notifyreg"?  Can you open the `~/.notifyreg` file and ensure the key is in there?

When you use the CLI, does it say "[notify] Notifying {key}" or nothing at all?

What platform are you on?

**Comment by mashlol** [comment]
Closing for now, please reopen if you are still encountering and can answer above questions

**Comment by stellarpower** [comment]
Sorry for the delay, no, it doesn't print anything it just ends silently. I don't have a .notifyreg file in my home folder. It works fine on my other machine. I'm on Mint 18.3 Sylvia, same as the machine on whihc it works succesfully. Does node have a logging system or anything I can check as it's not throwing any uncaught exceptions?

Thanks

**Comment by mashlol** [comment]
My guess is it doesn't have permission to write the `.notifyreg` file. Could you try running `notify -r xxx` w/ `sudo`?
