### ISSUE TITLE
Notifications are only shown if the app is in foreground

### ISSUE THREAD

**Issue by emanuele-f** [mashlol/notify#33]
Hello,
On android 8 (Oreo) the notifications are only shown while the app is in foreground. All the app notification permissions seem to be granted.

**Comment by mashlol** [comment]
Hmm, it works for me on Android 8. Which version of the app are you using? There were some issues in older versions

**Comment by emanuele-f** [comment]
I'm using latest version from the playstore (1.4)

**Comment by mashlol** [comment]
Oh, what about the CLI version? I think you also need the latest notify-cli npm version to get it to work properly in background.

**Comment by emanuele-f** [comment]
I was using version 0.1.3, updated to 0.1.4 and now it works, thank you!
