### ISSUE TITLE
Release a new version to play store

### ISSUE THREAD

**Issue by michaelkebe** [mashlol/notify#43]
I wanted to add longer notifications in the android app, but it was already done.

The version in the play store is an old one.

What about releasing a new version to the play store?

**Comment by andyforceno** [comment]
It's no longer on the Play store. Does anyone know if it's available somewhere else?

**Comment by mashlol** [comment]
Unfortunately Google took it down yesterday and I'm on vacation right now. Probably will sort it out in the next couple weeks. Until then you could build the apk yourself from source if you're comfortable doing that.

**Comment by djsuszi** [comment]
any news about android app ?

**Comment by mashlol** [comment]
All right, submitted a new version to Google, we'll see how long it takes them to accept it. Firebase automatically collects ad ID, and apparently you need some privacy policy if it does that...so I turned it off. I don't know why it collects that anyway...

**Comment by mashlol** [comment]
Seems to be approved
