### ISSUE TITLE
Custom text

### ISSUE THREAD

**Issue by AeroNotix** [mashlol/notify#5]
Would be nice if you could send your own text along with a notification

**Comment by mashlol** [comment]
Added -t or --text so you can specify a custom message:

`notify --text "My custom message"`

**Comment by AeroNotix** [comment]
Awesome, thanks!

**Comment by AeroNotix** [comment]
Sorry, but did this get pushed somewhere because I just reinstalled and my `notify` command claims `-t` is not an option.

**Comment by AeroNotix** [comment]
Working now, nevermind.
