### ISSUE TITLE
Spare communication channel for local Fire Department

### ISSUE THREAD

**Issue by lucks112** [mashlol/notify#55]
Hi

I would like to use Notify to inform a group of firefighters (15 persons) about alarm in our unit.
It will be use as a spare comms channel.
How I can inform a group of person instead of only on?

regards
Lukasz

**Comment by lucks112** [comment]
I'v found the soultion.
Sorry for interrupt

**Comment by mashlol** [comment]
Note that I would not rely on this for emergency situations! If you need to notify the firefighters urgently or reliably I would try to find a paid solution like texting/calling them with an automated service that provides reliability guarantees!

**Comment by lucks112** [comment]
> Note that I would not rely on this project for emergency situations! If you need to notify the firefighters urgently or reliably I would try to find a paid solution like texting/calling them with an automated service that provides reliability guarantees!

Yes, you have right.
That’s why i using notify as a stare channel
We have got very good solution based on RF channel to inform us about energency situation, but we would like to have spare - unofficial - channel
Thanks for reply and very nice app!

**Comment by mashlol** [comment]
Haha great to hear it! Glad you figured it out and are able to make use of it!
