### ISSUE TITLE
Notify not working anymore

### ISSUE THREAD

**Issue by MoikvanDoik** [mashlol/notify#58]
Hello,
is notify really not working anymore? If yes, is there a successor or simple alternative?
It worked perfectly until a few weeks ago.
Thank you

**Comment by johannesschauer97** [comment]
It stopped working for me too! :-/

**Comment by mashlol** [comment]
Looks like firebase doesn't allow node 6 anymore. I think newer node versions require a paid plan on firebase too, so not sure if the concept works anymore really.

![image](https://user-images.githubusercontent.com/1039240/113650149-99f75d80-9644-11eb-8991-464a33f65639.png)

**Comment by mashlol** [comment]
Eh, w.e, I set up billing since the rates are pretty high until they charge - hopefully I won't get charged. Hopefully it should work now - let me know if it's still broken.

**Comment by marekdolezel** [comment]
seems like it does not work anymore,  I am willing to donate if you setup a donate link

**Comment by mguinness** [comment]
Thanks for developing this app, but sad that it's no longer feasible to run.  As noted above it appears related to [Cloud Functions for Firebase support for Node 6 runtime will shut down](https://stackoverflow.com/questions/62053243) and a billing plan is required for Node.js 10 functions.  I assume that billing is the biggest issue preventing this project going forward?  I still think the concept is a good one as its simplicity is its main strength, but I understand if you don't want to go forward with it.
