### ISSUE TITLE
Does this use GCM?

### ISSUE THREAD

**Issue by DavidVentura** [mashlol/notify#8]
Hi, does this use GCM? If not, could you provide an APK?

**Comment by mashlol** [comment]
It uses parse, which in turn uses GCM.  Not sure why you wanting an APK is dependent on whether or not it uses GCM (don't want it going through Google's servers?), but you can build your own APK from the source code which is published at this repo, or download it from the play store.

**Comment by DavidVentura** [comment]
I don't have google services on my phone, if this didn't use them, it'd be easier to install if you provided an APK. Given that you are using GCM to push the notifications I can't use it anyway

**Comment by mashlol** [comment]
Hmm, I believe it will work regardless David, Parse has some logic which should fallback to some other service if GCM is not usable (Parse works on iOS, Amazon devices, etc).  According to https://github.com/ParsePlatform/Parse-SDK-Android/issues/35, it will fall back to a special Parse notification service if GCM is not available for use.  It might be worth a try!

**Comment by DavidVentura** [comment]
Awesome, I thought you'd use it for the push notifications. I'll look into this, thanks
